version: '3'
services:
  producer:
    build: ./metrics_generator/
    command: python producer.py --disk used --disk free --memory available
    environment:
      KAFKA_BROKER_URL: ${KAFKA_BROKER_URL}
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      KEYS_DIRECTORY: ../keys
    volumes:
    - ./keys/:/keys/
  consumer:
    build: ./metrics_consumer/
    command: python consumer.py
    environment:
      KAFKA_BROKER_URL: ${KAFKA_BROKER_URL}
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      KEYS_DIRECTORY: ../keys
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
    - ./keys/:/keys/


