version: '3'
services:
  producer:
    build: ./metrics_generator/
    command: python producer.py --disk used --disk free --memory available
    environment:
      KAFKA_BROKER_URL: ${KAFKA_BROKER_URL}
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      KEYS_DIRECTORY: ../keys


